name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Gradle Build and Test
        run: |
          cd RobotCode
          chmod +x ./gradlew
          ./gradlew build
          du -h build/libs/RobotCode.jar
          ./gradlew test
